# .github/workflows/deploy-pi-service.yml
name: Build and deploy Python app to Azure Web App - baduanjin-pi-service

on:
  push:
    branches:
      - main
    paths:  
      - 'pi-service/**'
      - '.github/workflows/deploy-pi-service.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4  

      - name: Set up Python version
        uses: actions/setup-python@v5  
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip  
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r pi-service/pi_requirements.txt  
        
      # Basic validation
      - name: Validate Pi Service
        run: |
          source venv/bin/activate
          cd pi-service
          python -c "from app.main import app; print('Pi Service validated successfully')"

      - name: Zip artifact for deployment
        run: |
          cd pi-service  # FIXED: Only zip pi-service directory
          zip -r ../release.zip . 

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4  
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4  
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2  
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}           
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}           
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3  
        id: deploy-to-webapp
        with:
          app-name: 'baduanjin-pi-service'
          slot-name: 'Production'

      # Post-deployment health check
      - name: 'Health Check'
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          curl -f https://baduanjin-pi-service.azurewebsites.net/health || echo "Health check failed - service might still be starting"
        continue-on-error: true